(function(){
'use strict';
const root=document.getElementById('examRoot'),K=window.PARTY_KNOWLEDGE;
if(!K){root.textContent='知识库未能完整加载，请联网后刷新。';return;}
const Q=K.points,TOPICS=K.topics,PARTS=['党的理论学习','党章、党纪党风','中国共产党历史','中国人民大学校史'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
let progress=read('party48_text_progress_v1',{});if(!progress||typeof progress!=='object'||Array.isArray(progress))progress={};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let settings=read('party_merged_plan_v1',{});if(!settings||typeof settings!=='object')settings={};
let start=/^\d{4}-\d{2}-\d{2}$/.test(settings.start)&&!isNaN(Date.parse(settings.start))?settings.start:today();
let duration=Number.isInteger(settings.duration)&&settings.duration>=5&&settings.duration<=30?settings.duration:12;
let schedule=K.makePlan(duration),selected=Math.max(0,Math.min(duration-1,Math.floor((new Date(today()+'T12:00:00')-new Date(start+'T12:00:00'))/86400000)));
let view='all',query='',topic='all',part='all',type='all',scope='all',recall=false;
const toggled=new Set(),notes=q=>q.annotations,types=q=>[...new Set(notes(q).flatMap(n=>n.types))];
const expansionPending=q=>K.expansionPending(q,progress);
const status=q=>K.getStatus(q,progress);
function store(){try{localStorage.setItem('party48_text_progress_v1',JSON.stringify(progress));}catch{document.getElementById('saveNotice').textContent='当前浏览器无法保存进度，刷新后可能丢失。';}}
const date=i=>{const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+i);return `${d.getMonth()+1}月${d.getDate()}日`;};
const dayPoints=d=>schedule[d].map(id=>Q.find(q=>q.id===id));
function resetFilters(){query='';topic='all';part='all';type='all';scope='all';recall=false;toggled.clear();}
function shell(){try{localStorage.setItem('party_merged_plan_v1',JSON.stringify({start,duration}));}catch{}root.innerHTML=`<section class="dashboard"><div><b id="totalProgress"></b><p>同一知识点合并背诵，出处和往期题型随时可查。</p></div><span class="material-status">48期资料待提供</span></section><p id="saveNotice" role="status"></p><nav class="views" aria-label="学习方式"><button data-view="all">知识总览</button><button data-view="day">每日背诵</button><button data-view="weak">待加强</button><button data-view="notes">题型与批注</button></nav><section id="dayIntro"></section><section id="planControls" hidden><label>首轮开始 <input id="planStart" aria-label="首轮开始日期" type="date" value="${esc(start)}"></label><label>首轮天数 <input id="planDuration" aria-label="首轮天数" type="number" min="5" max="30" value="${duration}"></label><p>包含全部${Q.length}个知识点，最后一天闭卷回顾。调整日期和天数不改变已保存的掌握程度。</p></section><div id="days" class="days" hidden></div><section id="topicOverview" aria-label="按专题学习"></section><div class="tools"><label class="search"><span>搜索整个知识库</span><input id="search" type="search" placeholder="知识点、关键词或原题号，如 47-1-71"></label><label>章节<select id="part"><option value="all">全部章节</option>${PARTS.map((p,i)=>`<option value="${i}">${p}</option>`).join('')}</select></label><label>来源与掌握<select id="scope"><option value="all">全部知识</option><option value="common">45、47期均收录</option><option value="only47">47期增加的知识</option><option value="expanded">47期扩写的知识</option><option value="pending">扩写内容待复习</option><option value="weak">尚未背熟</option><option value="mastered">已背熟</option></select></label><label>往期题型<select id="type"><option value="all">全部题型</option><option value="marked">有题型备注</option><option value="单选">单选</option><option value="多选">多选</option><option value="填空">填空</option><option value="默写">默写</option><option value="选择（未分单多）">选择（未分单多）</option><option value="unmarked">未注明题型</option></select></label><button id="recall">遮住正文自测</button><button id="clearFilters">清除筛选</button></div><p id="resultCount" role="status"></p><section id="questions" aria-label="知识点正文"></section>`;
root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;resetFilters();syncFilters();render();});
for(const id of ['part','scope','type'])document.getElementById(id).onchange=e=>{if(id==='part'){part=e.target.value;topic='all';}if(id==='scope')scope=e.target.value;if(id==='type')type=e.target.value;renderOverview();renderQuestions();};
document.getElementById('search').oninput=e=>{query=e.target.value.trim();renderQuestions();};
document.getElementById('clearFilters').onclick=()=>{resetFilters();syncFilters();renderOverview();renderQuestions();};
document.getElementById('recall').onclick=()=>{recall=!recall;toggled.clear();renderQuestions();};
const changePlan=()=>{const input=document.getElementById('planDuration'),n=Number(input.value),s=document.getElementById('planStart').value;if(!s||!Number.isInteger(n)||n<5||n>30){input.reportValidity();return;}start=s;duration=n;schedule=K.makePlan(duration);selected=Math.max(0,Math.min(duration-1,Math.floor((new Date(today()+'T12:00:00')-new Date(start+'T12:00:00'))/86400000)));try{localStorage.setItem('party_merged_plan_v1',JSON.stringify({start,duration}));}catch{document.getElementById('saveNotice').textContent='当前浏览器无法保存计划设置。';}resetFilters();syncFilters();render();};
document.getElementById('planStart').onchange=changePlan;document.getElementById('planDuration').onchange=changePlan;render();}
function syncFilters(){for(const [id,value] of Object.entries({search:query,part,scope,type}))document.getElementById(id).value=value;}
function updateProgress(){document.getElementById('totalProgress').textContent=`已背熟 ${Q.filter(q=>status(q)===2).length} / ${Q.length} 个知识点`;}
function render(){updateProgress();root.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});
const pending=Q.filter(expansionPending).length;
const intros={all:['45＋47期 · 合并知识库',`按${TOPICS.length}个专题组织${Q.length}个知识点。重复内容合并，47期增加与扩写的内容已纳入正文。`],weak:['先补齐薄弱点','集中复习未学习、需加强的知识点，以及尚未确认掌握的扩写内容。'],notes:['往期题型与批注','单选、多选、填空、默写来自47期手写备注；“考过”是原稿回忆，“可能考”是原稿推测。']};
const box=document.getElementById('dayIntro');
if(view==='day'){const list=dayPoints(selected),last=selected===duration-1;box.innerHTML=`<article class="intro"><span class="eyebrow">第 ${selected+1} 天 · ${date(selected)}</span><h2>${last?'全知识库闭卷回顾':'今天的背诵内容'}</h2><p>${last?'覆盖全部知识点':list.length+'个知识点 · 约'+list.reduce((s,q)=>s+q.text.length,0).toLocaleString()+'字'}，45、47期内容统一安排。</p><p>${last?'按标题复述；卡壳的标记“需加强”，随后集中重背。':'先回忆昨天内容，再分段学习今天内容，最后遮住正文复述。长题分层记忆，按实际掌握程度调整首轮天数。'}</p>${selected>0?'<button id="previousReview">闭卷复习前一天</button>':''}</article>`;const b=document.getElementById('previousReview');if(b)b.onclick=()=>{selected--;resetFilters();recall=true;syncFilters();render();};}
else{const [title,description]=intros[view];box.innerHTML=`<article class="intro"><h2>${title}</h2><p>${description}</p><p class="muted">备考目标：第48期；当前依据：第45、47期资料。收到48期资料后，再逐项核对新增、调整和未列入内容。</p>${pending?`<p class="update-notice">${pending}个已背过的知识点有47期扩写，已列入“待加强”；复习完整正文后重新标记即可。</p>`:''}</article>`;}
document.getElementById('planControls').hidden=view!=='day';const days=document.getElementById('days');days.hidden=view!=='day';days.innerHTML=view==='day'?schedule.map((ids,i)=>`<button class="day-button ${i===selected?'active':''}" data-day="${i}" aria-pressed="${i===selected}"><span>第${i+1}天 · ${date(i)}</span><strong>${i===duration-1?'闭卷回顾':ids.length+' 个'}</strong><small>${i===duration-1?'全部'+Q.length+'个知识点':[...new Set(dayPoints(i).map(q=>TOPICS.find(t=>t.id===q.topic).title))].join(' / ')}</small></button>`).join(''):'';
days.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.day);resetFilters();recall=selected===duration-1;syncFilters();render();});renderOverview();renderQuestions();}
function renderOverview(){const el=document.getElementById('topicOverview');el.hidden=view!=='all';if(view!=='all'){el.innerHTML='';return;}el.innerHTML=`<details class="topic-directory" open><summary>按专题学习 · ${topic==='all'?'全部专题':TOPICS.find(t=>t.id===topic).title}</summary><div class="topic-grid"><button data-topic="all" class="${topic==='all'?'active':''}">全部知识<span>${Q.length} 个</span></button>${TOPICS.filter(t=>part==='all'||t.part===Number(part)).map(t=>{const qs=Q.filter(q=>q.topic===t.id);return `<button data-topic="${t.id}" class="${topic===t.id?'active':''}"><b>${t.title}</b><span>${qs.filter(q=>status(q)===2).length} / ${qs.length} 已背熟</span><small>${t.description}</small></button>`;}).join('')}</div></details>`;el.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{topic=b.dataset.topic;renderOverview();renderQuestions();});}
const keywords=/两个先锋队|实现共产主义|实事求是|群众路线|独立自主|人民至上|自信自立|守正创新|问题导向|系统观念|胸怀天下|十个明确|十四个坚持|十三个方面成就|两个结合|两个确立|四个意识|四个自信|两个维护|五位一体|四个全面|中国式现代化|全心全意为人民服务|民主集中制|表决权|选举权|被选举权|预备期|党龄|首要任务|第一要务|第一生产力|第一资源|第一动力|根本保证|立德树人|为党育人|为国育才|为民造福|党性|十五五|[一二三四五六七八九十两〇0-9]+(?:年|月|日|项|种|个月|人以上)/g;
function fullText(text){return text.replace(/（([一二三四五六七八九十]+)）/g,'\n（$1）').split('\n').map(line=>`<p>${esc(line).replace(keywords,m=>'<mark>'+m+'</mark>')}</p>`).join('');}
function annotation(q){const ts=types(q);return `<aside class="source-notes" aria-label="来源与题型备注"><div class="type-badges">${ts.length?'<small>47期批注</small>'+ts.map(t=>`<span>${esc(t)}</span>`).join(''):'<small class="muted">未注明题型</small>'}</div>${notes(q).length?`<details ${view==='notes'?'open':''}><summary>查看原稿批注（${notes(q).length}条）</summary>${notes(q).map(n=>`<p><b>${esc(n.kind)}</b> · ${esc(n.text)} <span>47期第${n.page}页</span></p>`).join('')}</details>`:''}<details><summary>资料出处 · ${q.sources.length}处</summary>${q.sources.map(s=>`<p>${s.edition}期 · ${PARTS[s.part]} · 原第${s.number}题${s.page?` · 印刷第${s.page}页（PDF第${s.pdfPage}页）`:''}</p>`).join('')}</details></aside>`;}
function filtered(){let list=view==='day'&&!query?dayPoints(selected):view==='weak'?Q.filter(q=>status(q)!==2):view==='notes'?Q.filter(q=>notes(q).length):Q;
if(part!=='all')list=list.filter(q=>q.part===Number(part));if(topic!=='all')list=list.filter(q=>q.topic===topic);
if(type!=='all')list=list.filter(q=>type==='marked'?types(q).length:type==='unmarked'?!types(q).length:types(q).includes(type));
const scopes={common:q=>!q.only47,only47:q=>q.only47,expanded:q=>q.expanded,pending:expansionPending,weak:q=>status(q)!==2,mastered:q=>status(q)===2};if(scopes[scope])list=list.filter(scopes[scope]);
if(query){const key=query.toLowerCase();list=list.filter(q=>[q.title,q.text,PARTS[q.part],TOPICS.find(t=>t.id===q.topic).title,...q.progressIds,...q.versions.map(v=>v.text),...q.sources.map(s=>`${s.edition}-${s.part+1}-${s.number} 第${s.edition}期第${s.number}题`),...notes(q).map(n=>n.text+n.types.join(' '))].join(' ').toLowerCase().includes(key));}return list;}
function renderQuestions(){const list=filtered();document.getElementById('recall').textContent=recall?'显示全部正文':'遮住正文自测';document.getElementById('resultCount').textContent=`${view==='day'&&query?'已跨每日计划搜索 · ':''}显示 ${list.length} 个知识点 · ${list.filter(q=>status(q)===2).length} 个已背熟${topic!=='all'?' · '+TOPICS.find(t=>t.id===topic).title:''}`;
document.getElementById('questions').innerHTML=list.length?list.map(q=>{const hide=recall?!toggled.has(q.id):toggled.has(q.id);return `<article class="question ${status(q)===2?'mastered':''}" id="q-${q.id}"><div class="meta"><span>${PARTS[q.part]} / ${TOPICS.find(t=>t.id===q.topic).title}</span><span class="source-badge">${q.only47?'47期收录':'45、47期均收录'}</span>${q.expanded?'<span class="supplement-badge">47期扩写已并入</span>':''}${q.progressIds.length>1?'<span>重复知识已合并</span>':''}<span>${q.text.length}字</span></div><h3>${esc(q.title)}</h3>${expansionPending(q)?'<p class="update-notice">你背过的45期内容已保留掌握记录；请复习47期新增表述后重新确认。</p>':''}<div class="answer" id="answer-${q.id}" ${hide?'hidden':''}>${fullText(q.text)}${q.expanded||q.progressIds.length>1?`<details class="source-versions"><summary>查看合并前表述</summary>${q.versions.map(v=>`<h4>${v.edition}期 · ${PARTS[v.part]} · 原第${v.number}题</h4>${fullText(v.text)}`).join('')}</details>`:''}</div><p class="cover" ${hide?'':'hidden'}>根据标题复述，显示正文检查遗漏。</p>${annotation(q)}<details class="hint"><summary>理解与记忆提示</summary><p>${esc(q.hint)}</p></details><div class="actions"><button data-toggle="${q.id}" aria-controls="answer-${q.id}" aria-expanded="${!hide}">${hide?'显示完整正文':'遮住正文'}</button><label>掌握程度 <select data-status="${q.id}" aria-label="${esc(q.title)}掌握程度"><option value="0" ${status(q)===0?'selected':''}>未学习</option><option value="1" ${status(q)===1?'selected':''}>需加强</option><option value="2" ${status(q)===2?'selected':''}>已背熟</option></select></label></div></article>`;}).join(''):'<div class="empty">没有匹配的知识点。可清除筛选，或切换到知识总览。</div>';
root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const id=b.dataset.toggle;toggled.has(id)?toggled.delete(id):toggled.add(id);const ans=document.getElementById('answer-'+id);ans.hidden=!ans.hidden;ans.nextElementSibling.hidden=!ans.hidden;b.textContent=ans.hidden?'显示完整正文':'遮住正文';b.setAttribute('aria-expanded',String(!ans.hidden));});
root.querySelectorAll('[data-status]').forEach(el=>el.onchange=()=>{const q=Q.find(q=>q.id===el.dataset.status),n=Number(el.value);K.markProgress(q,n,progress);store();updateProgress();renderOverview();renderQuestions();});}
shell();
})();
